# 中文 GraphRAG 系統生產部署配置

# 基本部署設定
deployment_dir: "./deployment"
backup_dir: "./backups"

# 系統需求
required_disk_space_gb: 20
required_memory_gb: 8
required_commands:
  - "git"
  - "curl"
  - "uv"

# 網路連線測試
test_urls:
  - "https://www.google.com"
  - "https://api.openai.com"

# 生產環境配置
production_config:
  # 應用程式設定
  environment: "production"
  debug: false
  workers: 4
  
  # API 設定
  api:
    host: "0.0.0.0"
    port: 8000
    cors_enabled: false
    rate_limiting: true
    api_key_required: true
  
  # 日誌設定
  logging:
    level: "INFO"
    format: "json"
    rotation: "1 day"
    retention: "30 days"
    max_size: "100 MB"
  
  # 資料庫設定
  database:
    vector_db:
      type: "lancedb"
      path: "./data/vector_db"
      backup_interval: "6 hours"
    graph_db:
      path: "./data/graph_db"
      backup_interval: "12 hours"
  
  # Embedding 設定
  embedding:
    model: "BAAI/bge-m3"
    device: "auto"  # auto, cpu, cuda
    batch_size: 32
    cache_enabled: true
    cache_size: 1000
  
  # LLM 設定
  llm:
    provider: "openai"
    model: "gpt-5-mini"
    #temperature: 0.7
    #max_tokens: 2000
    timeout: 30
  
  # 中文處理設定
  chinese:
    jieba_dict_path: null
    stopwords_path: null
    enable_traditional: true
    enable_simplified: true
  
  # 效能設定
  performance:
    max_concurrent_requests: 100
    request_timeout: 300
    memory_limit_mb: 2048
    cpu_limit_percent: 80
  
  # 安全設定
  security:
    allowed_hosts: []
    cors_origins: []
    rate_limit_per_minute: 60
    max_request_size_mb: 10
  
  # 監控設定
  monitoring:
    enabled: true
    metrics_port: 9090
    health_check_port: 8080
    collect_interval: 60
    retention_days: 30
    
    # 警報閾值
    thresholds:
      cpu_percent: 80
      memory_percent: 85
      disk_percent: 90
      response_time_ms: 5000
      error_rate_percent: 5
    
    # 警報通道
    alerts:
      log: true
      email: false
      webhook: false
      slack: false

# 備份設定
backup:
  enabled: true
  schedule:
    daily: "02:00"    # 每天凌晨 2 點
    weekly: "03:00"   # 每週日凌晨 3 點
    monthly: "04:00"  # 每月 1 號凌晨 4 點
  
  retention:
    daily: 7
    weekly: 4
    monthly: 12
  
  compression: true
  encryption: false
  verify_backup: true
  
  # 遠端備份
  remote_backup:
    enabled: false
    type: "s3"  # s3, ftp, rsync
    config:
      bucket: "chinese-graphrag-backups"
      region: "us-west-2"
      access_key: ""
      secret_key: ""

# 服務設定
service:
  name: "chinese-graphrag"
  description: "中文 GraphRAG 知識圖譜系統"
  user: "graphrag"
  group: "graphrag"
  
  # 系統服務設定
  systemd:
    enabled: true
    restart_policy: "always"
    restart_delay: 10
    max_restarts: 5
  
  # 進程管理
  process:
    pid_file: "./run/chinese-graphrag.pid"
    log_file: "./logs/service.log"
    working_directory: "./deployment/app"

# 維護設定
maintenance:
  # 自動清理
  cleanup:
    logs_retention_days: 30
    cache_retention_days: 7
    temp_files_retention_hours: 24
  
  # 健康檢查
  health_check:
    enabled: true
    interval: 300  # 5 分鐘
    timeout: 30
    failure_threshold: 3
  
  # 自動重啟
  auto_restart:
    enabled: true
    memory_threshold_mb: 3072
    cpu_threshold_percent: 90
    error_threshold: 10

# 開發和測試設定
development:
  # 開發模式覆蓋設定
  debug: true
  workers: 1
  log_level: "DEBUG"
  
  # 測試資料
  test_data:
    enabled: false
    sample_documents: 10
    sample_queries: 20

# 部署後驗證
post_deployment:
  tests:
    - name: "API 健康檢查"
      type: "http"
      url: "http://localhost:8000/health"
      expected_status: 200
      timeout: 10
    
    - name: "資料庫連線"
      type: "database"
      check_vector_db: true
      check_graph_db: true
    
    - name: "Embedding 服務"
      type: "embedding"
      test_text: "測試中文文本處理"
      expected_dimension: 768
    
    - name: "查詢功能"
      type: "query"
      test_query: "什麼是人工智慧？"
      min_response_length: 50

# 環境變數範本
environment_variables:
  # 必要變數
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  
  # API 設定
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_WORKERS: "4"
  
  # 資料庫路徑
  DATA_DIR: "./data"
  VECTOR_DB_PATH: "./data/vector_db"
  GRAPH_DB_PATH: "./data/graph_db"
  
  # 日誌設定
  LOG_DIR: "./logs"
  LOG_LEVEL: "INFO"
  
  # 備份設定
  BACKUP_DIR: "./backups"
  BACKUP_ENABLED: "true"
  
  # 監控設定
  MONITORING_ENABLED: "true"
  METRICS_PORT: "9090"
  HEALTH_CHECK_PORT: "8080"
  
  # 安全設定
  API_KEY_REQUIRED: "true"
  RATE_LIMITING: "true"
  
  # 可選變數（需要用戶設定）
  OPENAI_API_KEY: ""
  AZURE_OPENAI_ENDPOINT: ""
  AZURE_OPENAI_API_KEY: ""
  
  # 自訂設定
  CUSTOM_CONFIG_PATH: "./config/custom.yaml"
  JIEBA_DICT_PATH: ""
  STOPWORDS_PATH: ""

# 文件和說明
documentation:
  deployment_guide: "./docs/deployment_guide.md"
  configuration_guide: "./docs/configuration_guide.md"
  troubleshooting_guide: "./docs/troubleshooting_guide.md"
  api_documentation: "./docs/api_documentation.md"

# 版本資訊
version_info:
  config_version: "1.0"
  compatible_app_versions: ["0.1.0", "0.2.0"]
  last_updated: "2025-01-08"
  author: "Chinese GraphRAG Team"